config/routes.rb
GoogleAuthExample::Application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :albums, only: [:index, :show] do
    resources :photos, only: [:index] do
      post :add_comment, on: :member
    end
  end

  root to: "home#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user
  
  def index
    data = JSON.load(RestClient.get("https://picasaweb.google.com/data/feed/api/user/default", {params: {alt: 'json'}, 'Authorization' => "OAuth #{current_user.oauth_token}", 'GData-Version' => 2}))
    @albums = data["feed"]["entry"].map{|e| {title: e["title"]["$t"], id: e["gphoto$id"]["$t"]}}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    redirect_to root_path(options) unless current_user.present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user

  def index
    data = JSON.load(RestClient.get("https://picasaweb.google.com/data/feed/api/user/default/albumid/#{params[:album_id]}", {params: {'max-results' => 3,alt: 'json'}, 'Authorization' => "OAuth #{current_user.oauth_token}", 'GData-Version' => 2}))
    @photos = data["feed"]["entry"].map{|e| {src: e["content"]["src"], id: e["gphoto$id"]["$t"]}}
    @album_title = data["feed"]["title"]["$t"]
  end

  def add_comment
    xml = <<-XML 
    <entry xmlns='http://www.w3.org/2005/Atom'>
	    <content>#{params[:comment]}</content>
      <category scheme='http://schemas.google.com/g/2005#kind'
        term='http://schemas.google.com/photos/2007#comment'/>
    </entry>
    XML
    url = "https://picasaweb.google.com/data/feed/api/user/default/albumid/#{params[:album_id]}/photoid/#{params[:id]}"
    resp = RestClient.post(url, xml, {content_type: 'application/atom+xml', 'Authorization' => "OAuth #{current_user.oauth_token}"})
    render nothing: true, status: :ok
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    current_user.present?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/albums/index.html.haml
%h2
  All Picasa Albums
%table.table.table-bordered.table-striped
  %tr
    %th Album
  - @albums.each do |album|
    %tr
      %td 
        = link_to album[:title], album_photos_path(album_id: album[:id])

app/views/home/show.html.haml
- if signed_in?
  = link_to "View all Picasa Albums", albums_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picasa Photo Viewer</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/photos/index.html.haml
%h2
  Photos from "#{@album_title}"
= link_to "View other albums", albums_path
%table.table.table-bordered
  %tr
    %th.span4 Photo
    %th.span8 Add Comment

    - @photos.each do |photo|
      %tr
        %td 
          = image_tag photo[:src]
        %td 
          = form_tag(add_comment_album_photo_path(id: photo[:id], album_id: params[:album_id]), remote: true) do |form|
            = text_field_tag :comment, '', placeholder: 'Enter new comment here',  autocomplete: 'off', size: 75, class: 'span6'
            = submit_tag 'Add Comment', autocomplete: 'off'
            = image_tag('ajax-loader.gif', class: 'spinner', style: 'display:none')